In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3], dtype='int16')    #int16 takes less memory than default int32
a

array([1, 2, 3], dtype=int16)

In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b.ndim

2

In [5]:
b.shape

(3, 3)

In [9]:
b.size

9

In [17]:
a[0,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [19]:
b[0,-1]     # negative index starts from end

3

In [21]:
b[:,2]

array([3, 6, 9])

In [23]:
c = np.array([[1,2,3,4,5,6,7],[11,22,33,44,55,66,77]])

In [38]:
c[0,0:-1:2]         # startindex:endindex:stepsize

array([1, 3, 5])

In [43]:
c[0,:]=1
c

array([[ 1,  1,  1,  1,  1,  1,  1],
       [11, 22, 33, 44, 55, 66, 77]])

In [46]:
c[0,:] = [1,2,3,4,5,6,7]
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [47]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [54]:
np.zeros((2,3,3))       #Also np.ones()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
np.full((2,2,3),3)  # Specify number

array([[[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]]])

In [57]:
np.full_like(d,3)       # makes with d's shape

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [59]:
# Random
np.random.rand(2,2,3)

array([[[0.87074356, 0.09112103, 0.55926639],
        [0.1636803 , 0.2414609 , 0.98960747]],

       [[0.48596428, 0.92528248, 0.70593249],
        [0.42478121, 0.51275898, 0.69798322]]])

In [62]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
arr = [[[1,2,3]]] # A 2D array
arr = np.repeat(arr, 3, axis=0)
arr

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [89]:
arr = np.repeat(arr, 3, axis=1)
arr

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [90]:
# The following does shallow copy so be careful
arr2 = arr
arr2

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [94]:
# Proof
arr2[0,0,0]=9999
arr

array([[[9999,    2,    3],
        [   1,    2,    3],
        [   1,    2,    3]],

       [[   1,    2,    3],
        [   1,    2,    3],
        [   1,    2,    3]],

       [[   1,    2,    3],
        [   1,    2,    3],
        [   1,    2,    3]]])

In [95]:
# For deep copy
arr2 = arr.copy()

In [97]:
arr2[0,0,0]=1
arr2

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [98]:
arr

array([[[9999,    2,    3],
        [   1,    2,    3],
        [   1,    2,    3]],

       [[   1,    2,    3],
        [   1,    2,    3],
        [   1,    2,    3]],

       [[   1,    2,    3],
        [   1,    2,    3],
        [   1,    2,    3]]])

# Mathematics Operations

In [115]:
a = np.array([1,2,3,4])
b= np.array([4,3,2,1])

In [106]:
a+b

array([5, 5, 5, 5])

In [114]:
a +=1
a

array([2, 3, 4, 5])

In [119]:
a = np.full((2,3),4)
b = np.full((3,4),3)

In [129]:
np.matmul(a,b)  # Matrix multiplication

array([[36, 36, 36, 36],
       [36, 36, 36, 36]])

# Statistics

In [134]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [136]:
c.max()

77

In [139]:
c.max(axis=1)

array([ 7, 77])

In [141]:
c.min(axis=0)

array([1, 2, 3, 4, 5, 6, 7])

In [147]:
c.sum(axis=1)

array([ 28, 308])

# Reorganize

In [150]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 66, 77]])

In [157]:
c.reshape(1,2,7)

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [11, 22, 33, 44, 55, 66, 77]]])

In [159]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

In [162]:
np.vstack([a,b])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [163]:
np.hstack([a,b])

array([1, 2, 3, 4, 4, 5, 6, 7])

In [164]:
np.vstack([a,b,a])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

# File Data

In [175]:
dt = np.genfromtxt('data.csv',delimiter=',',dtype='int32')
dt

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)

# Boolean Masking

In [174]:
dt[dt > 2]

array([3, 4, 4, 3, 5, 6, 7, 8], dtype=int32)

# Index to get [11,12][16,17] matrix

In [178]:
dt[2:4,:2]

array([[11, 12],
       [16, 17]], dtype=int32)